---
name: Lint
on:
  pull_request:

jobs:
  conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: webiny/action-conventional-commits@v1.3.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
